<?php

namespace Seat\HermesDj\Industry\Models\Profiles;

enum ProductionTypeEnum: string
{
    // MANUFACTURING
    case ADVANCED_COMPONENTS = 'ADVANCED_COMPONENTS';
    case LARGE_SHIPS = 'LARGE_SHIPS';
    case MEDIUM_SHIPS = 'MEDIUM_SHIPS';
    case SMALL_SHIPS = 'SMALL_SHIPS';
    case AMMO = 'AMMO';
    case BASIC_LARGE_SHIPS = 'BASIC_LARGE_SHIPS';
    case BASIC_MEDIUM_SHIPS = 'BASIC_MEDIUM_SHIPS';
    case BASIC_SMALL_SHIPS = 'BASIC_SMALL_SHIPS';
    case BIOCHEMICAL_REACTIONS = 'BIOCHEMICAL_REACTIONS';
    case COMPOSITE_REACTIONS = 'COMPOSITE_REACTIONS';
    case HYBRID_REACTIONS = 'HYBRID_REACTIONS';
    case CAPITAL_ADVANCED_COMPONENTS = 'CAPITAL_ADVANCED_COMPONENTS';
    case CAPITAL_COMPONENTS = 'CAPITAL_COMPONENTS';
    case CAPITAL_SHIPS = 'CAPITAL_SHIPS';
    case DRONES = 'DRONES';
    case EQUIPMENT = 'EQUIPMENT';
    case STRUCTURE = 'STRUCTURE';
    case ALL_SHIPS = 'ALL_SHIPS';
    case ALL_SHIP_COMPONENTS = 'ALL_SHIP_COMPONENTS';

    // RESEARCH
    case INVENTION = 'INVENTION';
    case RESEARCH_ME = 'RESEARCH_ME';
    case RESEARCH_TE = 'RESEARCH_TE';
    case COPY = 'COPY';

    // REACTIONS
    case HYBRID_REACTION = 'HYBRID_REACTION';
    case COMPOSITE_REACTION = 'COMPOSITE_REACTION';
    case BIOCHEMICAL_REACTION = 'BIOCHEMICAL_REACTION';

}
